### ISSUE TITLE
Date parsing issues since last update

### ISSUE THREAD

**Issue by achavez** [DallasMorningNews/chartwerk-editor#52]
I'm still trying to trace through the cause of this (may very well be on our end), but we have several charts that aren't rendering properly in the editor since the last update. Example (this chart has data, chatter, etc.):

![screen shot 2018-01-12 at 12 25 24 pm](https://user-images.githubusercontent.com/682828/34889470-b41f4d06-f793-11e7-894d-d34ee9a0681b.png)

There is an error in the console that I'm almost certain is the cause, but I haven't fully traced this back through React-land to figure out exactly why/how:

```
API ERROR TypeError: n.data[i][r].trim is not a function
    at e (BaseTypePicker.jsx:83)
    at Object.dateSniffer (BaseTypePicker.jsx:92)
    at Object.render (BaseTypePicker.jsx:130)
    at u._renderValidatedComponentWithoutOwnerOrContext (ReactCompositeComponent.js:799)
    at u._renderValidatedComponent (ReactCompositeComponent.js:822)
    at u.performInitialMount (ReactCompositeComponent.js:362)
    at u.mountComponent (ReactCompositeComponent.js:258)
    at Object.mountComponent (ReactReconciler.js:46)
    at f.mountChildren (ReactMultiChild.js:238)
    at f._createInitialChildren (ReactDOMComponent.js:697)
```

**Comment by achavez** [comment]
OK, clarifying the root cause of this a bit: It happens when the date sniffer encounters dates that are purely numeric and are therefore `Number`s, such as column of years:

```
Date	CBM	GQS
2015	45.47	32.84
2015	45.14	32.19
2015	49.05	34.23
2015	50.32	34.89
2015	49.25	36.48
```

FWIW, if I add a `.toString()` to [the offending `.trim()`](https://github.com/DallasMorningNews/chartwerk-editor/blob/f1e09dc60cd163cee46c0427837119cf1a993180/src/js/components/data/BaseTypePicker.jsx#L83) I end up with rendering errors in D3 so I'm sure there's some complexity to this I'm missing ...

**Comment by hobbes7878** [comment]
I _think_ I may have an idea why this happening...

So in updating `csvtojson` with the last PR I remember I consciously turned off type sniffing [here](https://github.com/DallasMorningNews/chartwerk-editor/blob/master/src/js/components/data/DataInput.jsx#L32). The idea is that all data should come through as strings and the template would then convert it to the correct type for the chart. Apparently those numeric dates are still coming through as numbers.

My instinct is to just ensure conversion to string at the line that's failing.

That may mean you'll also need to update your templates to expect strings instead of numeric types.

**Comment by hobbes7878** [comment]
Hmm... I'm **not** able to replicate the same issue on numeric dates with our line template using this data:

```
Month	Coal	Natural gas	Wind and solar
2003	51.26	15.83	0.73
2004	52.02	16.56	0.81
2005	51.33	16.22	1
2006	49.72	18.58	1.11
2007	49.08	18.88	0.96
2008	49.09	21.38	0.77
```

**Comment by achavez** [comment]
@hobbes7878 Weird. Thanks for looking at that. I'll dig deeper and see what I can figure out. For now we've gotten them working again by rolling back to 0.5.17.

**Comment by hobbes7878** [comment]
@achavez no problem. I'll hang on for what you find out in debugging. As soon as I can replicate an issue, happy to fix it.

**Comment by arianagiorgi** [comment]
After updating to 0.5.19 it seems the issue with the data disappearing on vertical line charts with dates is fixed, and works as expected in the line chart as well.
